version: '3'
services:
  web:
    image: senin-docker-image-ismin  => Oluşturduğumuz docker image web altında ayağı kalkacak.
    ports:
        - 8000:8000
    volumes:
        - ./:/app
    depends_on:
      - db
      - mongodb

  db:
    container_name: postgres_container  => Container ismi belirleniyor.
    image: postgres:12.0-alpine    => Docker içerisinden postgresql image alınıyor.
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: playstore
      PGDATA: /data/postgres
    volumes:
      - "./.docker/dbdata:/var/lib/postgresql/data"
    ports:
      - "5433:5433" => Container hangi portta çalışacak belirleniyor.

  pgadmin:
    container_name: pgadmin_container  => Container ismi belirleniyor.
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "omer@omer.com" => Pgadmin4 için kullanıcı adı ve şifre oluşturuluyor.
      PGADMIN_DEFAULT_PASSWORD: "q1w2e3"     => http://localhost:16543/ adrtesine gidersek pg4admin açılacak
    restart: unless-stopped
    ports:
      - "16543:80"
    depends_on:
      - db

  mongodb:
    container_name: mongodb_container  => Container ismi belirleniyor.
    image: mongo:latest
    ports:
      - "27017:27017"  => Projemizde mongo çalışyor artık.

volumes:
  pgdata:
